version: "3.3"
services:
  gobnilp:
    image: bpimages/gobnilp:4347c64
    command: tail -f /dev/null
  snakemake:
    image: snakemake/snakemake:stable
  trilearn:
    image: bpimages/trilearn:1.23-bp
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      DISPLAY: $DISPLAY
      MPLBACKEND: Agg
  notears:
    image: bpimages/jmoss20notears:1.4
    command: tail -f /dev/null
  benchpress:
    image: bpimages/benchpress:1.2.0
    working_dir: /myappdir
    command: jupyter lab --port 8080 --ip 0.0.0.0 --allow-root --no-browser
    volumes: 
        - ./:/myappdir/benchmark_local
    ports:
        - "8080:8080"
  datascience-python:
    image: civisanalytics/datascience-python
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      DISPLAY: $DISPLAY
      MPLBACKEND: Agg
  bidag:
    image: bpimages/bidag:2.0.2